class_name Loc
extends RefCounted
## Basit dil sistemi: Loc.t("anahtar") seçili dildeki metni döndürür.
## Her girdi [Türkçe, English] biçimindedir.

static var lang := "tr"

const TEXT := {
	"tagline": ["Bıçakları topla, halkanı büyüt, hayatta kal!", "Collect knives, grow your ring, survive!"],
	"characters": ["KARAKTERLER", "CHARACTERS"],
	"n_open": ["%d / %d açık", "%d / %d unlocked"],
	"play": ["OYNA", "PLAY"],
	"locked": ["KİLİTLİ", "LOCKED"],
	"unlock_need": ["%d leşte açılır", "Get %d kills to unlock"],
	"kills_progress": ["%d/%d leş", "%d/%d kills"],
	"sound_on": ["Ses: Açık", "Sound: On"],
	"sound_off": ["Ses: Kapalı", "Sound: Off"],
	"language": ["Türkçe", "English"],
	"stat_kills": ["Toplam leş", "Total kills"],
	"stat_wins": ["Galibiyet", "Wins"],
	"stat_best": ["En iyi", "Best"],
	"paused": ["OYUN DURDU", "PAUSED"],
	"resume": ["DEVAM", "RESUME"],
	"main_menu": ["ANA MENÜ", "MAIN MENU"],
	"retry": ["TEKRAR OYNA", "PLAY AGAIN"],
	"eliminated": ["ELENDİN!", "ELIMINATED!"],
	"won": ["KAZANDIN!", "VICTORY!"],
	"rank_line": ["Sıralama: #%d    Leş: %d", "Rank: #%d    Kills: %d"],
	"won_line": ["Arenada ayakta kalan son kişi sensin!    Leş: %d", "You rule the arena!    Kills: %d"],
	"new_unlock": ["Yeni karakter açıldı: %s!", "New character unlocked: %s!"],
	"alive": ["Hayatta: %d", "Alive: %d"],
	"zone_wait": ["Alan %d saniye sonra daralmaya başlıyor", "Zone shrinks in %ds"],
	"zone_shrink": ["Alan daralıyor, kırmızı bölgeden uzak dur!", "Zone shrinking! The red area hurts"],
	"zone_alert": ["ALAN DARALIYOR!", "ZONE SHRINKING!"],
	"leaders": ["Liderler", "Leaders"],
	"kills_short": ["Leş: %d", "Kills: %d"],
	"throw": ["FIRLAT", "THROW"],
	"you": ["Sen", "You"],
	"kill_popup": ["LEŞ!", "KILL!"],
	"pu_speed": ["Hız", "Speed"],
	"pu_shield": ["Kalkan", "Shield"],
	"pu_heal": ["Can", "Health"],
	"pu_magnet": ["Mıknatıs", "Magnet"],
	"pu_knives": ["+5 Bıçak", "+5 Knives"],
	"pu_bomb": ["Bomba aldın! FIRLAT ile at", "Bomb! Throw it"],
	"boss_name": ["DEV", "GIANT"],
	"boss_spawn": ["DEV ARENAYA GİRDİ! Onu yenen ödülü kapar!", "A GIANT BOSS APPEARED! Defeat it!"],
	"boss_down": ["%s Dev'i devirdi! +%d altın", "%s DEFEATED THE GIANT! +%d coins"],
	"tab_characters": ["KARAKTERLER", "CHARACTERS"],
	"tab_knives": ["BIÇAKLAR", "KNIVES"],
	"auto_aim_on": ["Otomatik nişan: Açık", "Auto-Aim: On"],
	"auto_aim_off": ["Otomatik nişan: Kapalı", "Auto-Aim: Off"],
	"knife_label": ["Bıçak: %s", "Blade: %s"],
	"buy": ["SATIN AL", "BUY"],
	"need_coins": ["%d altının olmalı", "Need %d coins"],
	"not_owned": ["Henüz senin değil", "Not owned"],
	"bought": ["Artık senin!", "PURCHASED!"],
	"name_placeholder": ["İsmini yaz...", "Enter your name..."],
	"name_label": ["Oyuncu adı", "Player name"],
	"default_name": ["Oyuncu", "Player"],
	"daily": ["Bugünün hediyesi: +%d altın!", "Daily reward: +%d coins!"],
	"reward_collected": ["Toplanan altın", "Coins collected"],
	"reward_kills": ["Leş bonusu", "Kill bonus"],
	"reward_rank": ["Sıralama bonusu", "Rank bonus"],
	"reward_time": ["Hayatta kalma süresi", "Survival"],
	"reward_total": ["TOPLAM", "TOTAL"],
	"tap_to_start": ["Başlamak için dokun", "Tap to start"],
	"multiplayer": ["ÇOK OYUNCULU", "MULTIPLAYER"],
	"admin": ["Yönetici", "Admin"],
	"mode_single": ["TEK OYUNCULU", "SINGLE PLAYER"],
	"mode_single_sub": ["Botlara karşı  •  Alan daralır", "Against bots  •  Shrinking zone"],
	"mode_multi": ["ÇOK OYUNCULU", "MULTIPLAYER"],
	"mode_multi_sub": ["Çevrimiçi arena  •  Gerçek oyuncular", "Online arena  •  Real players"],
	"equip": ["SEÇ", "EQUIP"],
	"equipped": ["KULLANILIYOR", "EQUIPPED"],
	"in_use": ["Seçili", "In use"],
	"settings": ["AYARLAR", "SETTINGS"],
	"fullscreen": ["Tam Ekran", "Fullscreen"],
	"scoreboard": ["SKOR TABLOSU", "SCOREBOARD"],
	"sb_player": ["Oyuncu", "Player"],
	"sb_kills": ["Leş", "Kills"],
	"sb_knives": ["Bıçak", "Knives"],
	"sb_hint": ["Kapatmak için dokun", "Tap to close"],
	"admin_title": ["YÖNETİCİ GİRİŞİ", "ADMIN LOGIN"],
	"admin_password": ["Yönetici şifresi", "Admin password"],
	"login": ["GİRİŞ", "LOG IN"],
	"logout": ["ÇIKIŞ", "LOG OUT"],
	"wrong_password": ["Şifre yanlış. Render'da ADMIN_PASSWORD tanımlı mı, kontrol et", "Wrong password or no admin password set on the server"],
	"admin_hint": ["Şifre: Render > knife-arena-server > Environment > ADMIN_PASSWORD", "Password: Render > knife-arena-server > Environment > ADMIN_PASSWORD"],
	"gift_coins": ["Yöneticiden hediye: +%d altın!", "The admin gifted you %d coins!"],
	"gift_level": ["Yöneticiden hediye: artık %d. seviyedesin!", "The admin raised your level: Lv. %d"],
	"ios_fullscreen": ["Tam ekran: Safari'de Paylaş butonu > Ana Ekrana Ekle, sonra oyunu ana ekrandan aç",
		"Fullscreen: in Safari tap Share > Add to Home Screen, then open the game from your home screen"],
	"connecting": ["Sunucuya bağlanıyoruz...", "Connecting to server..."],
	"joining": ["Arenaya giriyorsun...", "Joining the arena..."],
	"cancel": ["VAZGEÇ", "CANCEL"],
	"mp_failed": ["Sunucuya ulaşamadık, biraz sonra tekrar dene", "Could not connect to server"],
	"online": ["Arenada %d oyuncu", "Online: %d players"],
	"loading": ["Yükleniyor...", "Loading..."],
	"tab_levels": ["SEVİYE", "LEVELS"],
	"level_short": ["Sv. %d", "Lv. %d"],
	"level_req": ["%d. seviyede açılır", "Requires level %d"],
	"level_up": ["SEVİYE ATLADIN! Artık %d. seviyedesin", "LEVEL UP! Lv. %d"],
	"level_reward": ["+%d altın ödül kazandın", "+%d coin reward"],
	"xp_gained": ["+%d XP", "+%d XP"],
	"level_table_title": ["Seviye Ödülleri", "Level Rewards"],
	"level_unlocks": ["Kazanacakların: %s", "Unlocks: %s"],
	"current": ["ŞU AN", "NOW"],
	"done": ["Tamamlandı", "Claimed"],
	"dash": ["ATIL", "DASH"],
	"double_kill": ["ÇİFTE LEŞ!", "DOUBLE KILL!"],
	"triple_kill": ["ÜÇLÜ LEŞ!", "TRIPLE KILL!"],
	"multi_kill": ["KATLİAM!", "RAMPAGE!"],
	"streak_5": ["DURDURULAMAZ!", "UNSTOPPABLE!"],
	"streak_8": ["EFSANE!", "LEGENDARY!"],
	"event_coins": ["ALTIN YAĞMURU!", "GOLD RAIN!"],
	"event_knives": ["BIÇAK YAĞMURU!", "KNIFE RAIN!"],
	"event_boxes": ["GİZEMLİ KUTULAR GELDİ!", "MYSTERY BOXES!"],
	"box_knives": ["+8 BIÇAK!", "+8 KNIVES!"],
	"box_coins": ["HAZİNE!", "TREASURE!"],
	"box_rage": ["ÖFKE! Hasarın arttı", "RAGE! x1.6 DAMAGE"],
	"box_shoes": ["HIZ AYAKKABISI! 9 saniye uçarsın", "SPEED SHOES! 9 SEC"],
	"box_bomb": ["BOMBA! Hemen kaç!", "BOMB! RUN!"],
	"box_slow": ["Ayakların ağırlaştı!", "SLOWED!"],
	"box_thief": ["HIRSIZ! 4 bıçağını çaldı", "THIEF! -4 KNIVES"],
	"box_poison": ["ZEHİR BULUTU!", "POISON CLOUD!"],

	"knife_steel.name": ["Çelik Bıçak", "Steel Knife"],
	"knife_fire.name": ["Ateş Hançeri", "Fire Dagger"],
	"knife_ice.name": ["Buz Hançeri", "Frost Dagger"],
	"knife_poison.name": ["Zehirli Hançer", "Venom Dagger"],
	"knife_yatagan.name": ["Osmanlı Yatağanı", "Ottoman Yatagan"],
	"knife_thunder.name": ["Şimşek Bıçağı", "Thunder Blade"],
	"knife_void.name": ["Hiçlik Bıçağı", "Void Blade"],
	"knife_crimson.name": ["Kızıl Pala", "Crimson Blade"],

	"skin_keloglan.name": ["Keloğlan", "Keloglan"],
	"skin_keloglan.desc": ["Masalların akıllı kahramanı", "The clever hero of Turkish tales"],
	"skin_ninja.name": ["Ninja", "Ninja"],
	"skin_ninja.desc": ["Gölgelerin sessiz ustası", "Silent master of shadows"],
	"skin_knight.name": ["Şövalye", "Knight"],
	"skin_knight.desc": ["Sarsılmaz zırhın sahibi", "Clad in unbreakable armor"],
	"skin_frog.name": ["Kurbağa", "Frog"],
	"skin_frog.desc": ["Bataklığın zıplayan kralı", "Hopping king of the swamp"],
	"skin_pehlivan.name": ["Pehlivan", "Wrestler"],
	"skin_pehlivan.desc": ["Kırkpınar'ın yenilmez başpehlivanı", "Unbeaten champion of Kirkpinar"],
	"skin_pirate.name": ["Korsan", "Pirate"],
	"skin_pirate.desc": ["Yedi denizin belası", "Terror of the seven seas"],
	"skin_hoca.name": ["Nasreddin Hoca", "Nasreddin Hodja"],
	"skin_hoca.desc": ["Göle maya çalan bilge", "The wise man of a thousand jokes"],
	"skin_zeybek.name": ["Zeybek", "Zeybek"],
	"skin_zeybek.desc": ["Ege dağlarının yiğit efesi", "Brave warrior of the Aegean hills"],
	"skin_samurai.name": ["Samuray", "Samurai"],
	"skin_samurai.desc": ["Onuru için savaşır", "Fights for honor"],
	"skin_yeniceri.name": ["Yeniçeri", "Janissary"],
	"skin_yeniceri.desc": ["Osmanlı'nın seçkin askeri", "Elite soldier of the Ottomans"],
	"skin_viking.name": ["Viking", "Viking"],
	"skin_viking.desc": ["Kuzeyin dinmeyen öfkesi", "The endless fury of the north"],
	"skin_gokturk.name": ["Göktürk", "Gokturk"],
	"skin_gokturk.desc": ["Bozkırın gök bayraklı savaşçısı", "Sky-banner warrior of the steppe"],
	"skin_sultan.name": ["Padişah", "Sultan"],
	"skin_sultan.desc": ["Cihan imparatorluğunun hükümdarı", "Ruler of a world empire"],
	"skin_lale.name": ["Lale", "Lale"],
	"skin_lale.desc": ["Pembe tutkunu moda ikonu", "Pink-loving fashion icon"],
	"knife_heart.name": ["Kalp Hançeri", "Heart Dagger"],
	"knife_rose.name": ["Gül Hançeri", "Rose Dagger"],
	"female_only": ["Kadın karakterlere özel", "Female characters only"],
	"female_tag": ["KADIN", "FEMALE"],
	"female_need": ["Önce kadın karakter seç", "Pick a female character"],
	# Günlük görevler
	"daily_quests": ["GÜNLÜK GÖREVLER", "DAILY QUESTS"],
	"quests_renew": ["Her gün yenilenir", "Renews every day"],
	"q_kills": ["%d leş al", "Get %d kills"],
	"q_games": ["%d maç oyna", "Play %d matches"],
	"q_top3": ["Bir maçta ilk 3'e gir", "Finish top 3 in a match"],
	"q_boxes": ["%d gizemli kutu aç", "Open %d mystery boxes"],
	"q_coins": ["Arenadan %d altın topla", "Collect %d coins in the arena"],
	"claim": ["AL", "CLAIM"],
	"claimed": ["ALINDI", "DONE"],
	"quest_done": ["Görevi bitirdin! Ödülün Seviye sekmesinde seni bekliyor", "Quest complete! Claim it in the Levels tab"],
	"quest_reward": ["Ödülün geldi: +%d altın, +%d XP", "Quest reward: +%d coins, +%d XP"],
	"level_up_menu": ["Tebrikler, %d. seviyeye ulaştın!", "You reached level %d!"],
	# Seviye ödülleri (kıyafet / eşya)
	"level_items": ["SEVİYE EŞYALARI", "LEVEL ITEMS"],
	"acc_none.name": ["Yok", "None"],
	"acc_crown.name": ["Altın Taç", "Gold Crown"],
	"acc_aura.name": ["Ateş Aurası", "Fire Aura"],
	"acc_wings.name": ["Melek Kanadı", "Angel Wings"],
	"acc_halo.name": ["Işık Halesi", "Light Halo"],
	# Ana menü skor tablosu
	"lb_title": ["SKOR TABLOSU", "LEADERBOARD"],
	"lb_kills": ["LEŞ", "KILLS"],
	"lb_level": ["SEVİYE", "LEVEL"],
	"lb_coins": ["ALTIN", "COINS"],
	"lb_you": ["Sen", "You"],
	"announce": ["Yönetici: %s", "Admin: %s"],
	"chat_locked": ["Sohbet şu an yönetici tarafından kapatıldı", "Chat is closed by the admin"],
	"chat_muted": ["Sohbette susturuldun", "You are muted in chat"],
	"season_reset": ["Yeni sezon başladı! Seviyeler ve skorlar sıfırlandı, karakterlerin seninle", "New season! Levels and scores were reset, your items stay"],
	"admin_reset_you": ["Yönetici hesabındaki seviye ve skorları sıfırladı", "The admin reset your level and scores"],
	"chat_title": ["GENEL SOHBET", "GLOBAL CHAT"],
	"chat_placeholder": ["Mesaj yaz...", "Type a message..."],
	"chat_connecting": ["bağlanıyor...", "connecting..."],
	"chat_empty": ["Henüz kimse yazmadı. İlk merhabayı sen de!", "No messages yet. Say hi!"],
	"chat_need_name": ["Sohbete katılmak için önce ortadaki kutuya ismini yaz", "Enter your name to chat"],
	"chat_offline": ["Sohbet şu an kapalı, sunucu çevrimdışı", "Connecting to chat, please wait"],
	"lb_sp": ["TEK OYUNCU", "SINGLE"],
	"lb_mp": ["ÇOK OYUNCU", "ONLINE"],
	"lb_wins": ["ZAFER", "WINS"],
	"lb_best": ["REKOR", "RECORD"],
	"lb_goal": ["İlk 3'e girmene %d kaldı!", "%d more to reach the top 3!"],
	"lb_podium": ["Zirvedesin, yerini kaptırma!", "You're on the podium! Hold on"],
	"lb_empty": ["Liste sunucu açılınca gelecek", "The list loads when the server is online"],
	"chat_name_hint": ["Önce ortaya ismini yaz", "Enter your name first"],
	"srv_waking": ["Sunucu uyanıyor...", "Server waking up..."],
	"srv_online": ["Sunucu açık  •  %d oyuncu arenada", "Server online  •  %d in the arena"],
	"srv_offline": ["Sunucu şu an kapalı", "Server is offline"],
	"srv_outdated": ["Sunucu güncelleniyor", "Server is updating"],
	"mp_wait": ["Sunucu uyanıyor, birkaç saniye bekle", "The server is waking up, give it a few seconds"],
	"mp_offline": ["Çevrimiçi sunucu şu an kapalı. Biraz sonra tekrar dene", "The online server is down right now. Try again later"],
	"mp_outdated": ["Sunucu güncelleniyor, birkaç dakika sonra tekrar dene", "Server is updating, try again in a few minutes"],
}


static func t(key: String) -> String:
	var entry: Array = TEXT.get(key, [])
	if entry.is_empty():
		return key
	return entry[0] if lang == "tr" else entry[1]


## Kayıtta dil yoksa telefonun/bilgisayarın diline göre seçer.
static func detect() -> String:
	return "tr" if OS.get_locale_language() == "tr" else "en"
