class_name Loc
extends RefCounted
## Basit dil sistemi: Loc.t("anahtar") seçili dildeki metni döndürür.
## Her girdi [Türkçe, English] biçimindedir.

static var lang := "tr"

const TEXT := {
	"tagline": ["Bıçakları topla, halkanı büyüt, hayatta kal!", "Collect knives, grow your ring, survive!"],
	"characters": ["KARAKTERLER", "CHARACTERS"],
	"n_open": ["%d / %d açık", "%d / %d unlocked"],
	"play": ["OYNA", "PLAY"],
	"locked": ["KİLİTLİ", "LOCKED"],
	"unlock_need": ["Açmak için %d leş gerekli", "Get %d kills to unlock"],
	"kills_progress": ["%d/%d leş", "%d/%d kills"],
	"sound_on": ["Ses: Açık", "Sound: On"],
	"sound_off": ["Ses: Kapalı", "Sound: Off"],
	"language": ["Türkçe", "English"],
	"stat_kills": ["Toplam leş", "Total kills"],
	"stat_wins": ["Galibiyet", "Wins"],
	"stat_best": ["En iyi", "Best"],
	"paused": ["DURAKLATILDI", "PAUSED"],
	"resume": ["DEVAM", "RESUME"],
	"main_menu": ["ANA MENÜ", "MAIN MENU"],
	"retry": ["TEKRAR OYNA", "PLAY AGAIN"],
	"eliminated": ["ELENDİN!", "ELIMINATED!"],
	"won": ["KAZANDIN!", "VICTORY!"],
	"rank_line": ["Sıralama: #%d    Leş: %d", "Rank: #%d    Kills: %d"],
	"won_line": ["Arenanın tek hakimi sensin!    Leş: %d", "You rule the arena!    Kills: %d"],
	"new_unlock": ["Yeni karakter açıldı: %s!", "New character unlocked: %s!"],
	"alive": ["Kalan: %d", "Alive: %d"],
	"zone_wait": ["Alan %d sn sonra daralıyor", "Zone shrinks in %ds"],
	"zone_shrink": ["Alan daralıyor! Kırmızı bölge can yakar", "Zone shrinking! The red area hurts"],
	"zone_alert": ["ALAN DARALIYOR!", "ZONE SHRINKING!"],
	"leaders": ["Liderler", "Leaders"],
	"kills_short": ["Leş: %d", "Kills: %d"],
	"throw": ["FIRLAT", "THROW"],
	"you": ["Sen", "You"],
	"kill_popup": ["LEŞ!", "KILL!"],
	"pu_speed": ["Hız", "Speed"],
	"pu_shield": ["Kalkan", "Shield"],
	"pu_heal": ["Can", "Health"],
	"pu_magnet": ["Mıknatıs", "Magnet"],
	"pu_knives": ["+5 Bıçak", "+5 Knives"],
	"tab_characters": ["KARAKTERLER", "CHARACTERS"],
	"tab_knives": ["BIÇAKLAR", "KNIVES"],
	"auto_aim_on": ["Oto-Hedef: Açık", "Auto-Aim: On"],
	"auto_aim_off": ["Oto-Hedef: Kapalı", "Auto-Aim: Off"],
	"knife_label": ["Bıçak: %s", "Blade: %s"],
	"buy": ["SATIN AL", "BUY"],
	"need_coins": ["%d altın gerekli", "Need %d coins"],
	"not_owned": ["Satın alınmadı", "Not owned"],
	"bought": ["SATIN ALINDI!", "PURCHASED!"],
	"name_placeholder": ["İsmini yaz...", "Enter your name..."],
	"name_label": ["Oyuncu adı", "Player name"],
	"default_name": ["Oyuncu", "Player"],
	"daily": ["Günlük ödül: +%d altın!", "Daily reward: +%d coins!"],
	"reward_collected": ["Toplanan altın", "Coins collected"],
	"reward_kills": ["Leş bonusu", "Kill bonus"],
	"reward_rank": ["Sıralama bonusu", "Rank bonus"],
	"reward_time": ["Hayatta kalma", "Survival"],
	"reward_total": ["TOPLAM", "TOTAL"],
	"tap_to_start": ["Başlamak için dokun", "Tap to start"],
	"multiplayer": ["ÇOK OYUNCULU", "MULTIPLAYER"],
	"admin": ["Yönetici", "Admin"],
	"mode_single": ["TEK OYUNCULU", "SINGLE PLAYER"],
	"mode_single_sub": ["Botlara karşı  •  Alan daralır", "Against bots  •  Shrinking zone"],
	"mode_multi": ["ÇOK OYUNCULU", "MULTIPLAYER"],
	"mode_multi_sub": ["Çevrimiçi arena  •  Gerçek oyuncular", "Online arena  •  Real players"],
	"equip": ["SEÇ", "EQUIP"],
	"equipped": ["KULLANILIYOR", "EQUIPPED"],
	"in_use": ["Seçili", "In use"],
	"settings": ["AYARLAR", "SETTINGS"],
	"fullscreen": ["Tam Ekran", "Fullscreen"],
	"scoreboard": ["SKOR TABLOSU", "SCOREBOARD"],
	"sb_player": ["Oyuncu", "Player"],
	"sb_kills": ["Leş", "Kills"],
	"sb_knives": ["Bıçak", "Knives"],
	"sb_hint": ["Kapatmak için dokun", "Tap to close"],
	"admin_title": ["YÖNETİCİ GİRİŞİ", "ADMIN LOGIN"],
	"admin_password": ["Yönetici şifresi", "Admin password"],
	"login": ["GİRİŞ", "LOG IN"],
	"logout": ["ÇIKIŞ", "LOG OUT"],
	"wrong_password": ["Şifre yanlış ya da sunucuda yönetici şifresi ayarlı değil", "Wrong password or no admin password set on the server"],
	"admin_hint": ["Şifre: Render > knife-arena-server > Environment > ADMIN_PASSWORD", "Password: Render > knife-arena-server > Environment > ADMIN_PASSWORD"],
	"gift_coins": ["Yönetici sana %d altın hediye etti!", "The admin gifted you %d coins!"],
	"gift_level": ["Yönetici seviyeni yükseltti: Sv. %d", "The admin raised your level: Lv. %d"],
	"ios_fullscreen": ["Tam ekran: Safari'de Paylaş butonu > Ana Ekrana Ekle, sonra oyunu ana ekrandan aç",
		"Fullscreen: in Safari tap Share > Add to Home Screen, then open the game from your home screen"],
	"connecting": ["Sunucuya bağlanılıyor...", "Connecting to server..."],
	"joining": ["Arenaya giriliyor...", "Joining the arena..."],
	"cancel": ["VAZGEÇ", "CANCEL"],
	"mp_failed": ["Sunucuya bağlanılamadı", "Could not connect to server"],
	"online": ["Çevrimiçi: %d oyuncu", "Online: %d players"],
	"loading": ["Yükleniyor...", "Loading..."],
	"tab_levels": ["SEVİYE", "LEVELS"],
	"level_short": ["Sv. %d", "Lv. %d"],
	"level_req": ["Seviye %d gerekli", "Requires level %d"],
	"level_up": ["SEVİYE ATLADIN! Sv. %d", "LEVEL UP! Lv. %d"],
	"level_reward": ["+%d altın ödül", "+%d coin reward"],
	"xp_gained": ["+%d XP", "+%d XP"],
	"level_table_title": ["Seviye Ödülleri", "Level Rewards"],
	"level_unlocks": ["Açılır: %s", "Unlocks: %s"],
	"current": ["ŞU AN", "NOW"],
	"done": ["Alındı", "Claimed"],
	"dash": ["ATIL", "DASH"],
	"double_kill": ["ÇİFTE LEŞ!", "DOUBLE KILL!"],
	"triple_kill": ["ÜÇLÜ LEŞ!", "TRIPLE KILL!"],
	"multi_kill": ["KATLİAM!", "RAMPAGE!"],
	"streak_5": ["DURDURULAMAZ!", "UNSTOPPABLE!"],
	"streak_8": ["EFSANE!", "LEGENDARY!"],
	"event_coins": ["ALTIN YAĞMURU!", "GOLD RAIN!"],
	"event_knives": ["BIÇAK YAĞMURU!", "KNIFE RAIN!"],
	"event_boxes": ["GİZEMLİ KUTULAR GELDİ!", "MYSTERY BOXES!"],
	"box_knives": ["+8 BIÇAK!", "+8 KNIVES!"],
	"box_coins": ["HAZİNE!", "TREASURE!"],
	"box_rage": ["ÖFKE! x1.6 HASAR", "RAGE! x1.6 DAMAGE"],
	"box_bomb": ["BOMBA! KAÇ!", "BOMB! RUN!"],
	"box_slow": ["YAVAŞLADIN!", "SLOWED!"],
	"box_thief": ["HIRSIZ! -4 BIÇAK", "THIEF! -4 KNIVES"],
	"box_poison": ["ZEHİR BULUTU!", "POISON CLOUD!"],

	"knife_steel.name": ["Çelik Bıçak", "Steel Knife"],
	"knife_fire.name": ["Ateş Hançeri", "Fire Dagger"],
	"knife_ice.name": ["Buz Hançeri", "Frost Dagger"],
	"knife_poison.name": ["Zehirli Hançer", "Venom Dagger"],
	"knife_yatagan.name": ["Osmanlı Yatağanı", "Ottoman Yatagan"],
	"knife_thunder.name": ["Şimşek Bıçağı", "Thunder Blade"],
	"knife_void.name": ["Hiçlik Bıçağı", "Void Blade"],
	"knife_crimson.name": ["Kızıl Pala", "Crimson Blade"],

	"skin_keloglan.name": ["Keloğlan", "Keloglan"],
	"skin_keloglan.desc": ["Masalların akıllı kahramanı", "The clever hero of Turkish tales"],
	"skin_ninja.name": ["Ninja", "Ninja"],
	"skin_ninja.desc": ["Gölgelerin sessiz ustası", "Silent master of shadows"],
	"skin_knight.name": ["Şövalye", "Knight"],
	"skin_knight.desc": ["Sarsılmaz zırhın sahibi", "Clad in unbreakable armor"],
	"skin_frog.name": ["Kurbağa", "Frog"],
	"skin_frog.desc": ["Bataklığın zıplayan kralı", "Hopping king of the swamp"],
	"skin_pehlivan.name": ["Pehlivan", "Wrestler"],
	"skin_pehlivan.desc": ["Kırkpınar'ın yenilmez başpehlivanı", "Unbeaten champion of Kirkpinar"],
	"skin_pirate.name": ["Korsan", "Pirate"],
	"skin_pirate.desc": ["Yedi denizin belası", "Terror of the seven seas"],
	"skin_hoca.name": ["Nasreddin Hoca", "Nasreddin Hodja"],
	"skin_hoca.desc": ["Göle maya çalan bilge", "The wise man of a thousand jokes"],
	"skin_zeybek.name": ["Zeybek", "Zeybek"],
	"skin_zeybek.desc": ["Ege dağlarının yiğit efesi", "Brave warrior of the Aegean hills"],
	"skin_samurai.name": ["Samuray", "Samurai"],
	"skin_samurai.desc": ["Onuru için savaşır", "Fights for honor"],
	"skin_yeniceri.name": ["Yeniçeri", "Janissary"],
	"skin_yeniceri.desc": ["Osmanlı'nın seçkin askeri", "Elite soldier of the Ottomans"],
	"skin_viking.name": ["Viking", "Viking"],
	"skin_viking.desc": ["Kuzeyin dinmeyen öfkesi", "The endless fury of the north"],
	"skin_gokturk.name": ["Göktürk", "Gokturk"],
	"skin_gokturk.desc": ["Bozkırın gök bayraklı savaşçısı", "Sky-banner warrior of the steppe"],
	"skin_sultan.name": ["Padişah", "Sultan"],
	"skin_sultan.desc": ["Cihan imparatorluğunun hükümdarı", "Ruler of a world empire"],
}


static func t(key: String) -> String:
	var entry: Array = TEXT.get(key, [])
	if entry.is_empty():
		return key
	return entry[0] if lang == "tr" else entry[1]


## Kayıtta dil yoksa telefonun/bilgisayarın diline göre seçer.
static func detect() -> String:
	return "tr" if OS.get_locale_language() == "tr" else "en"
